import test from 'node:test'; import assert from 'node:assert/strict';
import { calculateStats, conflictsFor, effectiveTemplate, mergeBackup } from '../src/model.js';
test('学习统计不混入生活安排，也不凭完成状态编造用时',()=>{const tasks=[{id:'s',module:'AI',kind:'range',start:'09:00',end:'10:00',status:'done'},{id:'l',module:'生活',kind:'range',start:'10:00',end:'12:00',status:'done'}];const stats=calculateStats(tasks,[]);assert.deepEqual(stats,{done:1,total:1,improve:0,planned:3600,actual:0});});
test('实际用时只累计已结束记录',()=>{const tasks=[{id:'s',module:'AI',kind:'range',start:'09:00',end:'10:00',status:'todo'}];const stats=calculateStats(tasks,[{taskId:'s',endedAt:1,durationSeconds:300},{taskId:'s',durationSeconds:900}]);assert.equal(stats.actual,300);});
test('检测时间重叠但允许相邻任务',()=>{const base=[{id:'a',kind:'range',start:'09:00',end:'10:00',title:'A'}];assert.equal(conflictsFor({id:'b',kind:'range',start:'09:30',end:'10:30'},base).length,1);assert.equal(conflictsFor({id:'b',kind:'range',start:'10:00',end:'10:30'},base).length,0);});
test('模板按生效日期选择且不会改变日记录',()=>{const templates=[{id:'old',effectiveDate:'2026-01-01'},{id:'new',effectiveDate:'2026-02-01'}];assert.equal(effectiveTemplate(templates,'2026-01-20').id,'old');assert.equal(effectiveTemplate(templates,'2026-02-02').id,'new');});
test('合并备份按 ID 去重并保留本机版本',()=>{const current={templates:[{id:'x',v:1}],days:[],sessions:[{id:'same',durationSeconds:10}],settings:{timezone:'BJ'}};const incoming={templates:[{id:'x',v:2}],days:[],sessions:[{id:'same',durationSeconds:20},{id:'new',durationSeconds:5}],settings:{}};const merged=mergeBackup(current,incoming);assert.equal(merged.templates[0].v,1);assert.equal(merged.sessions.length,2);assert.equal(merged.sessions.find(x=>x.id==='same').durationSeconds,10);});
test('秒级时长不会把不足一分钟强制显示成一分钟', async()=>{const {formatDuration}=await import('../src/model.js');assert.equal(formatDuration(7),'7秒');assert.equal(formatDuration(67),'1分7秒');});
test('普通时间段要求结束晚于开始，时间点允许没有结束', async()=>{const {validTaskTime,sortTasks}=await import('../src/model.js');assert.equal(validTaskTime({kind:'range',start:'10:00',end:'09:00'}),false);assert.equal(validTaskTime({kind:'point',start:'06:55',end:''}),true);assert.deepEqual(sortTasks([{start:'10:00'},{start:'06:55'}]).map(x=>x.start),['06:55','10:00']);});
