import { STATUS, calculateStats, conflictsFor, effectiveTemplate, isStudy, plannedSeconds, taskActualSeconds, clone, formatDuration, sortTasks, validTaskTime, timerElapsed, reconcileTemplateDay, STUDY_MODULES } from './model.js?v=20260930-template-sync';
import * as db from './storage.js?v=20260930-hotfix';
const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
const control=(form,name)=>form.elements.namedItem(name);
const fmtDate=d=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(d); const todayBJ=()=>fmtDate(new Date());
const state={date:todayBJ(),day:null,sessions:[],selected:null,timer:null,pendingImport:null,templates:[],templateDraft:[],sessionToDelete:null,taskFormDirty:false,manualConfirm:false};
const uid=p=>`${p}-${Date.now()}-${crypto.randomUUID().slice(0,8)}`; const elapsed=t=>timerElapsed(t);
function notify(msg,error=false){const b=$('#banner');b.textContent=msg;b.className=`banner ${error?'error':''}`;clearTimeout(notify.t);notify.t=setTimeout(()=>b.classList.add('hidden'),5000)}
function escapeHtml(v=''){const d=document.createElement('div');d.textContent=v;return d.innerHTML} function clock(s){s=Math.floor(s);return [Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(x=>String(x).padStart(2,'0')).join(':')}
function dateLabel(date){return new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'long',day:'numeric',weekday:'long'}).format(new Date(`${date}T12:00:00+08:00`))}
async function persistDay(message='已保存到此设备'){try{await db.saveDay(state.day);notify(message)}catch(e){notify(`保存失败，输入仍保留在页面中：${e.message}`,true);throw e}}
const templateById=id=>state.templates.find(t=>t.id===id);
async function loadDate(date){state.date=date;state.templates=await db.getTemplates();const activeTemplate=effectiveTemplate(state.templates,date);state.sessions=await db.getSessions(date);state.timer=await db.getTimer();state.day=await db.getDay(date,activeTemplate);if(state.day.templateId!==activeTemplate.id){const protectedIds=state.sessions.map(s=>s.taskId).filter(Boolean);if(state.timer?.date===date)protectedIds.push(state.timer.taskId);const merged=reconcileTemplateDay(state.day,templateById(state.day.templateId)?.tasks||[],activeTemplate.tasks,{protectedIds});state.day={...merged.day,templateId:activeTemplate.id};await db.saveDay(state.day)}state.selected=state.day.tasks.some(t=>t.id===state.selected)?state.selected:null;render();showPendingTimer()}
function render(){ $('#datePicker').value=state.date;$('#dateTitle').textContent=state.date===todayBJ()?'今日计划':'计划与记录';$('#weekday').textContent=dateLabel(state.date);const stats=calculateStats(state.day.tasks,state.sessions);$('#stats').innerHTML=`<div class="progress-ring"><b>${stats.done}<small> / ${stats.total}</small></b><span>完成学习任务</span></div><div class="stat"><span>待完善</span><b>${stats.improve}</b></div><div class="stat"><span>计划学习</span><b>${formatDuration(stats.planned)}</b></div><div class="stat accent"><span>实际学习 · ${stats.sessions} 次</span><b>${formatDuration(stats.actual)}</b></div>`;
 $('#schedule').innerHTML=sortTasks(state.day.tasks).map(t=>{const active=state.timer?.taskId===t.id&&state.timer?.date===state.date;const actual=taskActualSeconds(t.id,state.sessions)+(active&&state.timer.phase!=='pending'?elapsed(state.timer):0);return `<button class="task-card ${state.selected===t.id?'selected':''} ${active?'timing':''}" data-id="${t.id}"><span class="time"><b>${t.start}</b><small>${t.kind==='range'?t.end:t.kind==='open'?'随后':'时间点'}</small></span><span class="line"></span><span class="task-copy"><span class="task-top"><b>${escapeHtml(t.title)}</b><i class="badge ${isStudy(t)?'study':''}">${escapeHtml(t.module)}</i>${active?'<i class="live">● 计时中</i>':''}</span><small>${escapeHtml(t.choice||t.note||'')}</small></span><span class="task-meta">${actual?`<small>历史 ${formatDuration(actual)}</small>`:''}<i class="status ${t.status}">${STATUS[t.status]}</i><span>›</span></span></button>`}).join('');$$('.task-card').forEach(x=>x.onclick=()=>{state.selected=x.dataset.id;render();if(innerWidth<1100)$('#detailPanel').scrollTo({top:0});});renderDetail();renderGlobalTimer() }
function renderDetail(){const t=state.day.tasks.find(x=>x.id===state.selected);$('#detailEmpty').classList.toggle('hidden',!!t);$('#detail').classList.toggle('hidden',!t);if(!t)return;const active=state.timer?.taskId===t.id&&state.timer?.date===state.date;const current=active?elapsed(state.timer):0;const history=taskActualSeconds(t.id,state.sessions);const list=state.sessions.filter(s=>s.taskId===t.id&&s.endedAt).sort((a,b)=>b.startedAt-a.startedAt);
 $('#detail').innerHTML=`<div class="detail-controls"><button class="icon-btn" id="editTask" aria-label="编辑任务">✎</button><button class="icon-btn close-detail" id="closeDetail" aria-label="关闭任务详情">×</button></div><div class="detail-head"><div><i class="badge ${isStudy(t)?'study':''}">${escapeHtml(t.module)}</i><h2>${escapeHtml(t.title)}</h2><p>${t.start}${t.end?`–${t.end}`:''} · ${t.kind==='point'?'时间点事项':t.kind==='open'?'无固定结束':formatDuration(plannedSeconds(t))}</p></div></div>${t.choice?`<div class="info-row"><span>当日选择</span><b>${escapeHtml(t.choice)}</b></div>`:''}<div class="note-box"><span>备注</span><p>${escapeHtml(t.note||'暂无备注')}</p></div><div class="status-picker"><span>完成状态</span><div>${Object.entries(STATUS).map(([k,v])=>`<button data-status="${k}" class="${t.status===k?'active':''}">${v}</button>`).join('')}</div></div>${isStudy(t)?`<section class="timer-card"><span>${active?(state.timer.phase==='pending'?'等待确认':state.timer.runningSince?'正在计时':'计时已暂停'):'本次计时'}</span><strong id="timerValue">${clock(current)}</strong><div class="timer-actions">${active&&state.timer.phase!=='pending'?`<button class="secondary" id="pauseTimer">${state.timer.runningSince?'暂停':'继续'}</button><button class="primary" id="endTimer">结束</button>`:active?'':`<button class="primary wide" id="startTimer">▷ 开始计时</button>`}</div><small>历史累计 ${formatDuration(history)}。计时与完成状态相互独立。</small></section><section class="sessions"><div class="section-title"><h3>练习记录</h3><button class="text-btn" id="manualDetailBtn">＋ 手动记录</button></div>${list.length?list.map(s=>`<div><span>${s.date} · ${s.source==='manual'?'手动录入':'系统计时'}${s.note?` · ${escapeHtml(s.note)}`:''}</span><span class="session-actions"><b>${formatDuration(s.durationSeconds)}</b>${s.source==='manual'?`<button class="text-btn" data-edit-session="${s.id}">修改</button>`:''}<button class="danger-link" data-delete-session="${s.id}">删除</button></span></div>`).join(''):'<p class="muted">还没有练习记录</p>'}</section>`:'<div class="non-study">生活安排不计入学习时长统计。</div>'}`;
 $('#closeDetail').onclick=closeDetail;$('#editTask').onclick=()=>openTask(t);$('#manualDetailBtn')?.addEventListener('click',()=>openManual(null,t));$$('[data-edit-session]').forEach(b=>b.onclick=()=>openManual(state.sessions.find(s=>s.id===b.dataset.editSession),t));$$('[data-status]').forEach(b=>b.onclick=async()=>{t.status=b.dataset.status;await persistDay('状态已保存');render()});$('#startTimer')?.addEventListener('click',()=>startTimer(t));$('#pauseTimer')?.addEventListener('click',togglePause);$('#endTimer')?.addEventListener('click',endTimer);$$('[data-delete-session]').forEach(b=>b.onclick=()=>requestDeleteSession(b.dataset.deleteSession,t)) }
function renderGlobalTimer(){const box=$('#globalTimer');if(!state.timer){box.classList.add('hidden');return}box.classList.remove('hidden');const status=state.timer.phase==='pending'?'等待保存':state.timer.runningSince?'正在计时':'已暂停';box.innerHTML=`<div><b>${escapeHtml(state.timer.taskTitle||'学习任务')}</b><small>${state.timer.date} · ${status}</small></div><strong id="globalTimerValue">${clock(elapsed(state.timer))}</strong><button class="secondary" id="openGlobalTimer">${state.timer.phase==='pending'?'处理记录':'查看计时'}</button>`;$('#openGlobalTimer').onclick=async()=>{if(state.timer.phase==='pending'){showPendingTimer();return}if(state.date!==state.timer.date)await loadDate(state.timer.date);state.selected=state.timer.taskId;render()}}
function closeDetail(){if($('#taskDialog').open&&state.taskFormDirty&&!confirm('编辑尚未保存。放弃修改并关闭吗？'))return;if($('#taskDialog').open)$('#taskDialog').close();state.selected=null;render()}
async function startTimer(t){if(state.timer){notify('已有计时或待确认记录，请先处理。',true);return}const now=Date.now(),timer={id:uid('timer'),taskId:t.id,taskTitle:t.title,module:t.module,date:state.date,startedAt:now,runningSince:now,accumulatedSeconds:0,phase:'active'};if(!await db.claimTimer(timer)){state.timer=await db.getTimer();render();notify('另一个页面已有计时，请先处理。',true);return}state.timer=timer;render()}
async function togglePause(){if(state.timer.runningSince){state.timer.accumulatedSeconds=elapsed(state.timer);state.timer.runningSince=null}else state.timer.runningSince=Date.now();await db.saveTimer(state.timer);render()}
async function endTimer(){if(!state.timer||state.timer.phase==='pending')return;state.timer.wasRunning=Boolean(state.timer.runningSince);state.timer.accumulatedSeconds=elapsed(state.timer);state.timer.runningSince=null;state.timer.phase='pending';await db.saveTimer(state.timer);render();showPendingTimer()}
function showPendingTimer(){if(state.timer?.phase!=='pending')return;const task=state.day?.tasks.find(t=>t.id===state.timer.taskId);$('#timerSaveError').classList.add('hidden');$('#timerConfirmSummary').innerHTML=`归属日期：<b>${state.timer.date}</b><br>任务：<b>${escapeHtml(state.timer.taskTitle||task?.title||'原计划任务')}</b><br>本次实际时长：<b>${formatDuration(state.timer.accumulatedSeconds)}</b>`;if(!$('#timerConfirmDialog').open)$('#timerConfirmDialog').showModal()}
$('#resumeTimer').onclick=async()=>{state.timer.phase='active';if(state.timer.wasRunning)state.timer.runningSince=Date.now();delete state.timer.wasRunning;await db.saveTimer(state.timer);$('#timerConfirmDialog').close();render()};
$('#discardTimer').onclick=async()=>{state.timer=null;await db.saveTimer(null);$('#timerConfirmDialog').close();render();notify('本次计时已放弃，未增加记录或统计')};
$('#saveTimerSession').onclick=async e=>{const button=e.currentTarget;if(button.disabled)return;button.disabled=true;const error=$('#timerSaveError');error.classList.add('hidden');try{const t=state.timer;if(!t||t.phase!=='pending')throw new Error('待确认计时已不存在，请刷新检查记录');const s={id:`session-${t.id||`${t.taskId}-${t.startedAt}`}`,source:'timer',taskId:t.taskId,taskTitle:t.taskTitle,module:t.module,date:t.date,startedAt:t.startedAt,endedAt:t.startedAt+t.accumulatedSeconds*1000,durationSeconds:t.accumulatedSeconds};await db.commitTimerSession(t,s);if(t.date===state.date&&!state.sessions.some(x=>x.id===s.id))state.sessions.push(s);state.timer=null;$('#timerConfirmDialog').close();render();notify('本次练习已保存')}catch(err){error.textContent=`保存失败：${err?.message||err}。计时数据仍完整保留，可以重试。`;error.classList.remove('hidden')}finally{button.disabled=false}};
function requestDeleteSession(id,t){const s=state.sessions.find(x=>x.id===id);state.sessionToDelete=id;$('#deleteSessionSummary').innerHTML=`任务：<b>${escapeHtml(t.title)}</b><br>日期：<b>${s.date}</b><br>时长：<b>${formatDuration(s.durationSeconds)}</b>`;$('#deleteSessionDialog').showModal()}
function cancelDelete(){state.sessionToDelete=null;$('#deleteSessionDialog').close()} $('#cancelDeleteSession').onclick=cancelDelete;$('#cancelDeleteSessionTop').onclick=cancelDelete;$('#confirmDeleteSession').onclick=async()=>{const id=state.sessionToDelete;if(!id)return;await db.deleteSession(id);state.sessions=state.sessions.filter(s=>s.id!==id);cancelDelete();render();notify('练习记录已删除，统计已更新')};
async function manualTasks(date){const templates=await db.getTemplates(),day=await db.getDay(date,effectiveTemplate(templates,date));return day.tasks.filter(isStudy)}
async function refreshManualTasks(selected=''){const form=$('#manualForm'),tasks=await manualTasks(control(form,'date').value);control(form,'taskId').innerHTML=`<option value="">不关联任务</option>${tasks.map(t=>`<option value="${t.id}" ${t.id===selected?'selected':''}>${escapeHtml(t.title)}（${escapeHtml(t.module)}）</option>`).join('')}`}
async function openManual(session=null,task=null){const f=$('#manualForm');f.reset();state.manualConfirm=false;control(f,'id').value=session?.id||'';control(f,'date').value=session?.date||state.date;control(f,'module').innerHTML=STUDY_MODULES.map(m=>`<option ${m===(session?.module||task?.module)?'selected':''}>${m}</option>`).join('');await refreshManualTasks(session?.taskId||task?.id||'');const seconds=session?.durationSeconds||0;control(f,'hours').value=Math.floor(seconds/3600);control(f,'minutes').value=Math.floor(seconds%3600/60);control(f,'seconds').value=seconds%60;control(f,'note').value=session?.note||'';$('#manualTitle').textContent=session?'修改手动练习记录':'手动添加练习记录';$('#manualPreview').textContent='填写后点击“检查并确认”，确认内容后再次保存。';$('#manualError').classList.add('hidden');$('#saveManual').textContent='检查并确认';$('#manualDialog').showModal()}
function closeManual(){state.manualConfirm=false;$('#manualDialog').close()}$('#manualBtn').onclick=()=>openManual();$('#closeManual').onclick=closeManual;$('#cancelManual').onclick=closeManual;control($('#manualForm'),'date').onchange=()=>refreshManualTasks();$('#manualForm').addEventListener('input',()=>{state.manualConfirm=false;$('#saveManual').textContent='检查并确认'});
$('#manualForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,seconds=Number(control(f,'hours').value||0)*3600+Number(control(f,'minutes').value||0)*60+Number(control(f,'seconds').value||0),error=$('#manualError');error.classList.add('hidden');if(seconds<=0){error.textContent='实际时长必须大于 0 秒。';error.classList.remove('hidden');return}const task=(await manualTasks(control(f,'date').value)).find(t=>t.id===control(f,'taskId').value);if(!state.manualConfirm){$('#manualPreview').innerHTML=`请确认：<b>${control(f,'date').value}</b> · <b>${escapeHtml(control(f,'module').value)}</b> · <b>${formatDuration(seconds)}</b>${task?` · ${escapeHtml(task.title)}`:' · 不关联任务'}`;state.manualConfirm=true;$('#saveManual').textContent='确认保存';return}const button=$('#saveManual');button.disabled=true;try{const oldId=control(f,'id').value,id=oldId||uid('manual'),now=Date.now();await db.saveSession({id,source:'manual',date:control(f,'date').value,module:control(f,'module').value,taskId:control(f,'taskId').value||null,taskTitle:task?.title||'',durationSeconds:seconds,note:control(f,'note').value.trim(),startedAt:now,endedAt:now,updatedAt:now});if(control(f,'date').value===state.date){const i=state.sessions.findIndex(s=>s.id===id),saved={id,source:'manual',date:control(f,'date').value,module:control(f,'module').value,taskId:control(f,'taskId').value||null,taskTitle:task?.title||'',durationSeconds:seconds,note:control(f,'note').value.trim(),startedAt:now,endedAt:now,updatedAt:now};i>=0?state.sessions[i]=saved:state.sessions.push(saved)}closeManual();render();notify(oldId?'手动记录已更新，统计已重新计算':'手动记录已保存并计入统计')}catch(err){error.textContent=`保存失败：${err?.message||err}`;error.classList.remove('hidden')}finally{button.disabled=false}};
function formTask(){const f=$('#taskForm'),data=Object.fromEntries(new FormData(f)),old=state.day.tasks.find(t=>t.id===data.id);return{...old,id:data.id||uid('task'),title:data.title,module:data.module,kind:data.kind,start:data.start,end:data.kind==='range'?data.end:'',note:data.note,reminder:control(f,'reminder').checked,status:old?.status||'todo',choice:data.choice||'',choices:old?.choices}}
function showConflicts(){const c=conflictsFor(formTask(),state.day.tasks);$('#conflicts').classList.toggle('hidden',!c.length);$('#conflicts').textContent=c.length?`时间与“${c.map(x=>x.title).join('、')}”重叠。仍可保存，请自行调整安排。`:''}
function openTask(t=null){const f=$('#taskForm');f.reset();control(f,'id').value=t?.id||'';control(f,'title').value=t?.title||'';control(f,'module').value=t?.module||'生活';control(f,'kind').value=t?.kind||'range';control(f,'start').value=t?.start||'09:00';control(f,'end').value=t?.end||'10:00';control(f,'note').value=t?.note||'';control(f,'reminder').checked=t?.reminder||false;$('#formTitle').textContent=t?'编辑当天任务':'新增当天任务';$('#deleteTask').classList.toggle('hidden',!t);$('#choiceWrap').classList.toggle('hidden',!t?.choices);if(t?.choices)control(f,'choice').innerHTML=t.choices.map(x=>`<option ${x===t.choice?'selected':''}>${x}</option>`).join('');state.taskFormDirty=false;$('#taskDialog').showModal();showConflicts()}
$('#taskForm').addEventListener('input',()=>{state.taskFormDirty=true;showConflicts()});$$('#taskForm [value=cancel]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();if(state.taskFormDirty&&!confirm('放弃尚未保存的编辑吗？'))return;state.taskFormDirty=false;$('#taskDialog').close()}));$('#taskForm').addEventListener('submit',async e=>{e.preventDefault();const t=formTask();if(!validTaskTime(t)){notify('普通时间段的结束时间必须晚于开始时间',true);return}const i=state.day.tasks.findIndex(x=>x.id===t.id);i>=0?state.day.tasks[i]=t:state.day.tasks.push(t);state.day.tasks=sortTasks(state.day.tasks);await persistDay();state.taskFormDirty=false;$('#taskDialog').close();state.selected=t.id;render()});
$('#deleteTask').onclick=async()=>{const id=control($('#taskForm'),'id').value;if(!confirm('只删除这项当天计划？练习记录和固定模板不会改变。'))return;state.day.tasks=state.day.tasks.filter(x=>x.id!==id);state.selected=null;await persistDay('当天任务已删除');$('#taskDialog').close();render()};
function renderTemplateDraft(){const modules=['生活','化妆','剪辑','调色','英语／雅思','AI','拍摄'];$('#templateTasks').innerHTML=state.templateDraft.map((t,i)=>`<div class="template-row" data-template-index="${i}"><label>名称<input data-field="title" required value="${escapeHtml(t.title)}"></label><label>模块<select data-field="module">${modules.map(m=>`<option ${m===t.module?'selected':''}>${m}</option>`).join('')}</select></label><label>开始<input data-field="start" type="time" required value="${t.start}"></label><label>结束（可空）<input data-field="end" type="time" value="${t.end||''}"></label><label>备注<input data-field="note" value="${escapeHtml(t.note||'')}"></label><button type="button" class="icon-btn remove-template" aria-label="删除模板安排">×</button></div>`).join('');$$('.template-row input,.template-row select').forEach(x=>x.oninput=()=>{const row=x.closest('.template-row');state.templateDraft[+row.dataset.templateIndex][x.dataset.field]=x.value});$$('.remove-template').forEach(x=>x.onclick=()=>{state.templateDraft.splice(+x.closest('.template-row').dataset.templateIndex,1);renderTemplateDraft()})}
function updateTemplateImpact(){const date=control($('#templateForm'),'effectiveDate').value;const before=state.date<date;$('#templateImpact').innerHTML=before?`当前查看的 ${state.date} 早于生效日期，当前日程不会变化。<button type="button" class="text-btn" id="jumpEffectiveDate">跳转到生效日期</button>`:`保存后会立即更新当前查看日期 ${state.date} 的时间表，并同步生效范围内未单独修改的已生成计划。`;$('#jumpEffectiveDate')?.addEventListener('click',()=>{ $('#templateDialog').close();loadDate(date) })}
$('#templateBtn').onclick=()=>{const template=effectiveTemplate(state.templates,state.date);state.templateDraft=clone(template.tasks);control($('#templateForm'),'effectiveDate').value=state.date;renderTemplateDraft();updateTemplateImpact();$('#templateDialog').showModal()};
control($('#templateForm'),'effectiveDate').onchange=updateTemplateImpact;
$('#addTemplateTask').onclick=()=>{state.templateDraft.push({id:uid('task'),title:'新安排',module:'生活',kind:'point',start:'09:00',end:'',note:'',reminder:false,status:'todo'});renderTemplateDraft()};
$('#templateForm').onsubmit=async e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();for(const t of state.templateDraft){t.kind=t.end?'range':'point';if(!validTaskTime(t)){notify(`“${t.title}”的结束时间必须晚于开始时间`,true);return}}const date=control(e.currentTarget,'effectiveDate').value;if(!confirm(`将从该日期起使用新模板，并更新该日期的时间表。\n\n生效日期：${date}\n确认保存吗？`))return;const template={id:uid('template'),effectiveDate:date,tasks:sortTasks(state.templateDraft).map(t=>({...t,status:'todo'})),createdAt:Date.now()};const prospective=[...state.templates,template];const generated=(await db.getDays()).filter(day=>effectiveTemplate(prospective,day.date)?.id===template.id);const sessions=await db.getAllSessions();const timer=await db.getTimer();const previews=generated.map(day=>{const prior=state.templates.find(t=>t.id===day.templateId);const protectedIds=sessions.filter(s=>s.date===day.date).map(s=>s.taskId).filter(Boolean);if(timer?.date===day.date)protectedIds.push(timer.taskId);return {original:day,result:reconcileTemplateDay(day,prior?.tasks||[],template.tasks,{protectedIds})}});const conflicts=previews.filter(x=>x.result.hasCustomizations);let preserveCustom=true;if(conflicts.length){const dates=conflicts.slice(0,5).map(x=>x.original.date).join('、');preserveCustom=confirm(`检测到 ${conflicts.length} 个日期有用户单独新增或修改的内容（${dates}${conflicts.length>5?' 等':''}）。\n\n“确定”保留这些单独修改，只更新其余模板安排；“取消”使用新模板覆盖这些单独修改。\n\n完成状态、练习记录和当前计时关联始终保留。`) }await db.saveTemplate(template);const updated=previews.map(({original,result})=>{const next=preserveCustom?result:reconcileTemplateDay(original,state.templates.find(t=>t.id===original.templateId)?.tasks||[],template.tasks,{preserveCustom:false,protectedIds:[...sessions.filter(s=>s.date===original.date).map(s=>s.taskId),timer?.date===original.date?timer.taskId:null].filter(Boolean)});return {...next.day,templateId:template.id}});await db.saveDays(updated);state.templates=await db.getTemplates();$('#templateDialog').close();await loadDate(state.date);notify(state.date<date?`模板已保存，从 ${date} 起生效；当前日程未变化`:`模板已保存，${state.date} 的时间表已更新`)};
$('#addTask').onclick=()=>openTask();$('#datePicker').onchange=e=>loadDate(e.target.value);$('#todayBtn').onclick=()=>loadDate(todayBJ());const shift=n=>{const d=new Date(`${state.date}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+n);loadDate(fmtDate(d))};$('#prevDay').onclick=()=>shift(-1);$('#nextDay').onclick=()=>shift(1);
$$('[data-later]').forEach(b=>b.onclick=()=>notify(`${b.dataset.later}模块后续接入，本阶段没有无效占位功能。`));$('#settingsBtn').onclick=()=>$('#settingsDialog').showModal();$('#exportBtn').onclick=async()=>{const data=await db.exportAll(),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=`学习系统备份-${todayBJ()}.json`;a.click();URL.revokeObjectURL(a.href)};$('#importFile').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(data.schemaVersion!==1||!Array.isArray(data.templates)||!Array.isArray(data.days))throw new Error('备份格式不兼容');state.pendingImport=data;$('#importChoice').classList.remove('hidden')}catch(err){notify(`无法读取备份：${err.message}`,true)}};$('#mergeImport').onclick=async()=>{await db.importMerged(state.pendingImport);$('#settingsDialog').close();await loadDate(state.date);notify('备份已合并；相同 ID 的本机记录优先保留')};$('#replaceImport').onclick=async()=>{if(!confirm('确定用备份替换此设备的全部数据吗？建议先导出当前数据。'))return;await db.replaceAll(state.pendingImport);$('#settingsDialog').close();await loadDate(state.date);notify('已用备份替换本机数据')};
setInterval(()=>{if(state.timer?.runningSince){const val=$('#timerValue');if(val)val.textContent=clock(elapsed(state.timer));const global=$('#globalTimerValue');if(global)global.textContent=clock(elapsed(state.timer))}},1000);window.addEventListener('unhandledrejection',e=>notify(`操作失败，页面中的内容仍保留：${e.reason?.message||e.reason}`,true));
async function boot(){try{await db.initialize(todayBJ());await loadDate(state.date)}catch(error){const banner=$('#banner');banner.className='banner error';banner.innerHTML=`初始化失败：${escapeHtml(error?.message||String(error))}。现有数据未被清除或覆盖。 <button type="button" id="retryBoot">重试</button>`;$('#retryBoot').onclick=boot}}
await boot();
