import { STATUS, calculateStats, conflictsFor, effectiveTemplate, isStudy, plannedSeconds, taskActualSeconds, clone, formatDuration, sortTasks, validTaskTime } from './model.js';
import * as db from './storage.js';
const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
const fmtDate=d=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(d); const todayBJ=()=>fmtDate(new Date());
const state={date:todayBJ(),day:null,sessions:[],selected:null,timer:null,pendingImport:null,templates:[],templateDraft:[],sessionToDelete:null,taskFormDirty:false};
const uid=p=>`${p}-${Date.now()}-${crypto.randomUUID().slice(0,8)}`; const elapsed=t=>t?t.accumulatedSeconds+(t.runningSince?Math.max(0,Math.floor((Date.now()-t.runningSince)/1000)):0):0;
function notify(msg,error=false){const b=$('#banner');b.textContent=msg;b.className=`banner ${error?'error':''}`;clearTimeout(notify.t);notify.t=setTimeout(()=>b.classList.add('hidden'),5000)}
function escapeHtml(v=''){const d=document.createElement('div');d.textContent=v;return d.innerHTML} function clock(s){s=Math.floor(s);return [Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(x=>String(x).padStart(2,'0')).join(':')}
function dateLabel(date){return new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'long',day:'numeric',weekday:'long'}).format(new Date(`${date}T12:00:00+08:00`))}
async function persistDay(message='已保存到此设备'){try{await db.saveDay(state.day);notify(message)}catch(e){notify(`保存失败，输入仍保留在页面中：${e.message}`,true);throw e}}
async function loadDate(date){state.date=date;state.templates=await db.getTemplates();state.day=await db.getDay(date,effectiveTemplate(state.templates,date));state.sessions=await db.getSessions(date);state.timer=await db.getTimer();state.selected=state.day.tasks.some(t=>t.id===state.selected)?state.selected:null;render();showPendingTimer()}
function render(){ $('#datePicker').value=state.date;$('#dateTitle').textContent=state.date===todayBJ()?'今日计划':'计划与记录';$('#weekday').textContent=dateLabel(state.date);const stats=calculateStats(state.day.tasks,state.sessions);$('#stats').innerHTML=`<div class="progress-ring"><b>${stats.done}<small> / ${stats.total}</small></b><span>完成学习任务</span></div><div class="stat"><span>待完善</span><b>${stats.improve}</b></div><div class="stat"><span>计划学习</span><b>${formatDuration(stats.planned)}</b></div><div class="stat accent"><span>实际学习</span><b>${formatDuration(stats.actual)}</b></div>`;
 $('#schedule').innerHTML=sortTasks(state.day.tasks).map(t=>{const active=state.timer?.taskId===t.id&&state.timer?.date===state.date;const actual=taskActualSeconds(t.id,state.sessions)+(active&&state.timer.phase!=='pending'?elapsed(state.timer):0);return `<button class="task-card ${state.selected===t.id?'selected':''} ${active?'timing':''}" data-id="${t.id}"><span class="time"><b>${t.start}</b><small>${t.kind==='range'?t.end:t.kind==='open'?'随后':'时间点'}</small></span><span class="line"></span><span class="task-copy"><span class="task-top"><b>${escapeHtml(t.title)}</b><i class="badge ${isStudy(t)?'study':''}">${escapeHtml(t.module)}</i>${active?'<i class="live">● 计时中</i>':''}</span><small>${escapeHtml(t.choice||t.note||'')}</small></span><span class="task-meta">${actual?`<small>历史 ${formatDuration(actual)}</small>`:''}<i class="status ${t.status}">${STATUS[t.status]}</i><span>›</span></span></button>`}).join('');$$('.task-card').forEach(x=>x.onclick=()=>{state.selected=x.dataset.id;render();if(innerWidth<1100)$('#detailPanel').scrollTo({top:0});});renderDetail() }
function renderDetail(){const t=state.day.tasks.find(x=>x.id===state.selected);$('#detailEmpty').classList.toggle('hidden',!!t);$('#detail').classList.toggle('hidden',!t);if(!t)return;const active=state.timer?.taskId===t.id&&state.timer?.date===state.date;const current=active?elapsed(state.timer):0;const history=taskActualSeconds(t.id,state.sessions);const list=state.sessions.filter(s=>s.taskId===t.id&&s.endedAt).sort((a,b)=>b.startedAt-a.startedAt);
 $('#detail').innerHTML=`<div class="detail-head"><div><i class="badge ${isStudy(t)?'study':''}">${escapeHtml(t.module)}</i><h2>${escapeHtml(t.title)}</h2><p>${t.start}${t.end?`–${t.end}`:''} · ${t.kind==='point'?'时间点事项':t.kind==='open'?'无固定结束':formatDuration(plannedSeconds(t))}</p></div><div class="detail-controls"><button class="icon-btn" id="editTask" aria-label="编辑任务">✎</button><button class="icon-btn close-detail" id="closeDetail" aria-label="关闭任务详情">×</button></div></div>${t.choice?`<div class="info-row"><span>当日选择</span><b>${escapeHtml(t.choice)}</b></div>`:''}<div class="note-box"><span>备注</span><p>${escapeHtml(t.note||'暂无备注')}</p></div><div class="status-picker"><span>完成状态</span><div>${Object.entries(STATUS).map(([k,v])=>`<button data-status="${k}" class="${t.status===k?'active':''}">${v}</button>`).join('')}</div></div>${isStudy(t)?`<section class="timer-card"><span>${active?(state.timer.phase==='pending'?'等待确认':state.timer.runningSince?'正在计时':'计时已暂停'):'本次计时'}</span><strong id="timerValue">${clock(current)}</strong><div class="timer-actions">${active&&state.timer.phase!=='pending'?`<button class="secondary" id="pauseTimer">${state.timer.runningSince?'暂停':'继续'}</button><button class="primary" id="endTimer">结束</button>`:active?'':`<button class="primary wide" id="startTimer">▷ 开始计时</button>`}</div><small>历史累计 ${formatDuration(history)}。计时与完成状态相互独立。</small></section><section class="sessions"><h3>练习记录</h3>${list.length?list.map(s=>`<div><span>${new Date(s.startedAt).toLocaleDateString('zh-CN',{timeZone:'Asia/Shanghai'})} ${new Date(s.startedAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Shanghai'})}</span><span class="session-actions"><b>${formatDuration(s.durationSeconds)}</b><button class="danger-link" data-delete-session="${s.id}">删除</button></span></div>`).join(''):'<p class="muted">还没有计时记录</p>'}</section>`:'<div class="non-study">生活安排不计入学习时长统计。</div>'}`;
 $('#closeDetail').onclick=closeDetail;$('#editTask').onclick=()=>openTask(t);$$('[data-status]').forEach(b=>b.onclick=async()=>{t.status=b.dataset.status;await persistDay('状态已保存');render()});$('#startTimer')?.addEventListener('click',()=>startTimer(t));$('#pauseTimer')?.addEventListener('click',togglePause);$('#endTimer')?.addEventListener('click',endTimer);$$('[data-delete-session]').forEach(b=>b.onclick=()=>requestDeleteSession(b.dataset.deleteSession,t)) }
function closeDetail(){if($('#taskDialog').open&&state.taskFormDirty&&!confirm('编辑尚未保存。放弃修改并关闭吗？'))return;if($('#taskDialog').open)$('#taskDialog').close();state.selected=null;render()}
async function startTimer(t){if(state.timer){notify('已有计时或待确认记录，请先处理。',true);return}state.timer={taskId:t.id,date:state.date,startedAt:Date.now(),runningSince:Date.now(),accumulatedSeconds:0,phase:'active'};await db.saveTimer(state.timer);render()}
async function togglePause(){if(state.timer.runningSince){state.timer.accumulatedSeconds=elapsed(state.timer);state.timer.runningSince=null}else state.timer.runningSince=Date.now();await db.saveTimer(state.timer);render()}
async function endTimer(){if(!state.timer||state.timer.phase==='pending')return;state.timer.wasRunning=Boolean(state.timer.runningSince);state.timer.accumulatedSeconds=elapsed(state.timer);state.timer.runningSince=null;state.timer.phase='pending';await db.saveTimer(state.timer);render();showPendingTimer()}
function showPendingTimer(){if(state.timer?.phase!=='pending')return;const task=state.day?.tasks.find(t=>t.id===state.timer.taskId);$('#timerConfirmSummary').innerHTML=`任务：<b>${escapeHtml(task?.title||'原计划任务')}</b><br>本次实际时长：<b>${formatDuration(state.timer.accumulatedSeconds)}</b>`;if(!$('#timerConfirmDialog').open)$('#timerConfirmDialog').showModal()}
$('#resumeTimer').onclick=async()=>{state.timer.phase='active';if(state.timer.wasRunning)state.timer.runningSince=Date.now();delete state.timer.wasRunning;await db.saveTimer(state.timer);$('#timerConfirmDialog').close();render()};
$('#discardTimer').onclick=async()=>{state.timer=null;await db.saveTimer(null);$('#timerConfirmDialog').close();render();notify('本次计时已放弃，未增加记录或统计')};
$('#saveTimerSession').onclick=async e=>{e.currentTarget.disabled=true;try{const t=state.timer;if(!t||t.phase!=='pending')return;const s={id:`session-${t.taskId}-${t.startedAt}`,taskId:t.taskId,date:t.date,startedAt:t.startedAt,endedAt:Date.now(),durationSeconds:t.accumulatedSeconds};await db.saveSession(s);if(t.date===state.date&&!state.sessions.some(x=>x.id===s.id))state.sessions.push(s);state.timer=null;await db.saveTimer(null);$('#timerConfirmDialog').close();render();notify('本次练习已保存')}finally{e.currentTarget.disabled=false}};
function requestDeleteSession(id,t){const s=state.sessions.find(x=>x.id===id);state.sessionToDelete=id;$('#deleteSessionSummary').innerHTML=`任务：<b>${escapeHtml(t.title)}</b><br>日期：<b>${s.date}</b><br>时长：<b>${formatDuration(s.durationSeconds)}</b>`;$('#deleteSessionDialog').showModal()}
function cancelDelete(){state.sessionToDelete=null;$('#deleteSessionDialog').close()} $('#cancelDeleteSession').onclick=cancelDelete;$('#cancelDeleteSessionTop').onclick=cancelDelete;$('#confirmDeleteSession').onclick=async()=>{const id=state.sessionToDelete;if(!id)return;await db.deleteSession(id);state.sessions=state.sessions.filter(s=>s.id!==id);cancelDelete();render();notify('练习记录已删除，统计已更新')};
function formTask(){const f=$('#taskForm'),data=Object.fromEntries(new FormData(f)),old=state.day.tasks.find(t=>t.id===data.id);return{...old,id:data.id||uid('task'),title:data.title,module:data.module,kind:data.kind,start:data.start,end:data.kind==='range'?data.end:'',note:data.note,reminder:f.reminder.checked,status:old?.status||'todo',choice:data.choice||'',choices:old?.choices}}
function showConflicts(){const c=conflictsFor(formTask(),state.day.tasks);$('#conflicts').classList.toggle('hidden',!c.length);$('#conflicts').textContent=c.length?`时间与“${c.map(x=>x.title).join('、')}”重叠。仍可保存，请自行调整安排。`:''}
function openTask(t=null){const f=$('#taskForm');f.reset();f.id.value=t?.id||'';f.title.value=t?.title||'';f.module.value=t?.module||'生活';f.kind.value=t?.kind||'range';f.start.value=t?.start||'09:00';f.end.value=t?.end||'10:00';f.note.value=t?.note||'';f.reminder.checked=t?.reminder||false;$('#formTitle').textContent=t?'编辑当天任务':'新增当天任务';$('#deleteTask').classList.toggle('hidden',!t);$('#choiceWrap').classList.toggle('hidden',!t?.choices);if(t?.choices)f.choice.innerHTML=t.choices.map(x=>`<option ${x===t.choice?'selected':''}>${x}</option>`).join('');state.taskFormDirty=false;$('#taskDialog').showModal();showConflicts()}
$('#taskForm').addEventListener('input',()=>{state.taskFormDirty=true;showConflicts()});$('#taskForm').addEventListener('submit',async e=>{if(e.submitter?.value==='cancel'){if(state.taskFormDirty&&!confirm('放弃尚未保存的编辑吗？'))e.preventDefault();return}e.preventDefault();const t=formTask();if(!validTaskTime(t)){notify('普通时间段的结束时间必须晚于开始时间',true);return}const i=state.day.tasks.findIndex(x=>x.id===t.id);i>=0?state.day.tasks[i]=t:state.day.tasks.push(t);state.day.tasks=sortTasks(state.day.tasks);await persistDay();state.taskFormDirty=false;$('#taskDialog').close();state.selected=t.id;render()});
$('#deleteTask').onclick=async()=>{const id=$('#taskForm').id.value;if(!confirm('只删除这项当天计划？练习记录和固定模板不会改变。'))return;state.day.tasks=state.day.tasks.filter(x=>x.id!==id);state.selected=null;await persistDay('当天任务已删除');$('#taskDialog').close();render()};
function renderTemplateDraft(){const modules=['生活','化妆','剪辑','调色','英语／雅思','AI','拍摄'];$('#templateTasks').innerHTML=state.templateDraft.map((t,i)=>`<div class="template-row" data-template-index="${i}"><label>名称<input data-field="title" required value="${escapeHtml(t.title)}"></label><label>模块<select data-field="module">${modules.map(m=>`<option ${m===t.module?'selected':''}>${m}</option>`).join('')}</select></label><label>开始<input data-field="start" type="time" required value="${t.start}"></label><label>结束（可空）<input data-field="end" type="time" value="${t.end||''}"></label><label>备注<input data-field="note" value="${escapeHtml(t.note||'')}"></label><button type="button" class="icon-btn remove-template" aria-label="删除模板安排">×</button></div>`).join('');$$('.template-row input,.template-row select').forEach(x=>x.oninput=()=>{const row=x.closest('.template-row');state.templateDraft[+row.dataset.templateIndex][x.dataset.field]=x.value});$$('.remove-template').forEach(x=>x.onclick=()=>{state.templateDraft.splice(+x.closest('.template-row').dataset.templateIndex,1);renderTemplateDraft()})}
$('#templateBtn').onclick=()=>{const template=effectiveTemplate(state.templates,state.date);state.templateDraft=clone(template.tasks);$('#templateForm').effectiveDate.value=state.date<todayBJ()?todayBJ():state.date;renderTemplateDraft();$('#templateDialog').showModal()};$('#addTemplateTask').onclick=()=>{state.templateDraft.push({id:uid('task'),title:'新安排',module:'生活',kind:'point',start:'09:00',end:'',note:'',reminder:false,status:'todo'});renderTemplateDraft()};
$('#templateForm').onsubmit=async e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();for(const t of state.templateDraft){t.kind=t.end?'range':'point';if(!validTaskTime(t)){notify(`“${t.title}”的结束时间必须晚于开始时间`,true);return}}const date=e.currentTarget.effectiveDate.value;if(!confirm(`新模板将从 ${date} 起，仅用于尚未生成的计划。已生成的当天或未来计划、历史状态和练习记录均不覆盖。确认保存吗？`))return;await db.saveTemplate({id:uid('template'),effectiveDate:date,tasks:sortTasks(state.templateDraft).map(t=>({...t,status:'todo'})),createdAt:Date.now()});state.templates=await db.getTemplates();$('#templateDialog').close();notify(`模板已保存，将从 ${date} 起用于尚未生成的计划`)};
$('#addTask').onclick=()=>openTask();$('#datePicker').onchange=e=>loadDate(e.target.value);$('#todayBtn').onclick=()=>loadDate(todayBJ());const shift=n=>{const d=new Date(`${state.date}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+n);loadDate(fmtDate(d))};$('#prevDay').onclick=()=>shift(-1);$('#nextDay').onclick=()=>shift(1);
$$('[data-later]').forEach(b=>b.onclick=()=>notify(`${b.dataset.later}模块后续接入，本阶段没有无效占位功能。`));$('#settingsBtn').onclick=()=>$('#settingsDialog').showModal();$('#exportBtn').onclick=async()=>{const data=await db.exportAll(),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=`学习系统备份-${todayBJ()}.json`;a.click();URL.revokeObjectURL(a.href)};$('#importFile').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(data.schemaVersion!==1||!Array.isArray(data.templates)||!Array.isArray(data.days))throw new Error('备份格式不兼容');state.pendingImport=data;$('#importChoice').classList.remove('hidden')}catch(err){notify(`无法读取备份：${err.message}`,true)}};$('#mergeImport').onclick=async()=>{await db.importMerged(state.pendingImport);$('#settingsDialog').close();await loadDate(state.date);notify('备份已合并；相同 ID 的本机记录优先保留')};$('#replaceImport').onclick=async()=>{if(!confirm('确定用备份替换此设备的全部数据吗？建议先导出当前数据。'))return;await db.replaceAll(state.pendingImport);$('#settingsDialog').close();await loadDate(state.date);notify('已用备份替换本机数据')};
setInterval(()=>{if(state.timer?.runningSince){const val=$('#timerValue');if(val)val.textContent=clock(elapsed(state.timer))}},1000);window.addEventListener('unhandledrejection',e=>notify(`操作失败，页面中的内容仍保留：${e.reason?.message||e.reason}`,true));await db.initialize(todayBJ());await loadDate(state.date);
