import { STATUS, calculateStats, conflictsFor, effectiveTemplate, isStudy, plannedSeconds, taskActualSeconds, clone } from './model.js';
import * as db from './storage.js';

const $ = s => document.querySelector(s); const fmtDate = d => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Shanghai', year: 'numeric', month: '2-digit', day: '2-digit' }).format(d); const todayBJ = () => fmtDate(new Date());
const state = { date: todayBJ(), day: null, sessions: [], selected: null, timer: null, pendingImport: null, templates: [] };
const uid = p => `${p}-${Date.now()}-${crypto.randomUUID().slice(0, 8)}`;
const duration = sec => { const m = Math.floor(sec / 60); return m >= 60 ? `${Math.floor(m / 60)}小时${m % 60 ? `${m % 60}分` : ''}` : `${m}分钟`; };
const elapsed = timer => timer ? timer.accumulatedSeconds + (timer.runningSince ? Math.max(0, Math.floor((Date.now() - timer.runningSince) / 1000)) : 0) : 0;
function notify(msg, error = false) { const b = $('#banner'); b.textContent = msg; b.className = `banner ${error ? 'error' : ''}`; clearTimeout(notify.t); notify.t = setTimeout(() => b.classList.add('hidden'), 5000); }
async function persistDay(message = '已保存到此设备') { try { await db.saveDay(state.day); notify(message); } catch (e) { notify(`保存失败，输入仍保留在页面中：${e.message}`, true); throw e; } }
function dateLabel(date) { const d = new Date(`${date}T12:00:00+08:00`); return new Intl.DateTimeFormat('zh-CN', { timeZone: 'Asia/Shanghai', month: 'long', day: 'numeric', weekday: 'long' }).format(d); }

async function loadDate(date) { state.date = date; state.templates = await db.getTemplates(); const template = effectiveTemplate(state.templates, date); state.day = await db.getDay(date, template); state.sessions = await db.getSessions(date); state.timer = await db.getTimer(); state.selected = state.day.tasks.find(t => t.id === state.selected)?.id || null; render(); }
function render() {
  $('#datePicker').value = state.date; $('#dateTitle').textContent = state.date === todayBJ() ? '今日计划' : '计划与记录'; $('#weekday').textContent = dateLabel(state.date);
  const stats = calculateStats(state.day.tasks, state.sessions);
  $('#stats').innerHTML = `<div class="progress-ring"><b>${stats.done}<small> / ${stats.total}</small></b><span>完成学习任务</span></div><div class="stat"><span>待完善</span><b>${stats.improve}</b></div><div class="stat"><span>计划学习</span><b>${duration(stats.planned)}</b></div><div class="stat accent"><span>实际学习</span><b>${duration(stats.actual)}</b></div>`;
  const tasks = [...state.day.tasks].sort((a,b) => a.start.localeCompare(b.start));
  $('#schedule').innerHTML = tasks.map(t => { const active = state.timer?.taskId === t.id && state.timer?.date === state.date; const actual = taskActualSeconds(t.id, state.sessions) + (active ? elapsed(state.timer) : 0); return `<button class="task-card ${state.selected === t.id ? 'selected' : ''} ${active ? 'timing' : ''}" data-id="${t.id}"><span class="time"><b>${t.start}</b><small>${t.kind === 'range' ? t.end : t.kind === 'open' ? '随后' : '时间点'}</small></span><span class="line"></span><span class="task-copy"><span class="task-top"><b>${escapeHtml(t.title)}</b><i class="badge ${isStudy(t) ? 'study' : ''}">${escapeHtml(t.module)}</i>${active ? '<i class="live">● 正在计时</i>' : ''}</span><small>${escapeHtml(t.choice || t.note || (t.reminder ? '到点提醒已保存 · 设备通知尚未启用' : ''))}</small></span><span class="task-meta">${actual ? `<small>实际 ${duration(actual)}</small>` : ''}<i class="status ${t.status}">${STATUS[t.status]}</i><span>›</span></span></button>`; }).join('');
  document.querySelectorAll('.task-card').forEach(x => x.onclick = () => { state.selected = x.dataset.id; render(); if (innerWidth < 1100) $('#detailPanel').scrollIntoView({ behavior: 'smooth' }); }); renderDetail();
}
function renderDetail() { const t = state.day.tasks.find(x => x.id === state.selected); $('#detailEmpty').classList.toggle('hidden', !!t); $('#detail').classList.toggle('hidden', !t); if (!t) return; const active = state.timer?.taskId === t.id && state.timer?.date === state.date; const seconds = taskActualSeconds(t.id, state.sessions) + (active ? elapsed(state.timer) : 0); const sessionList = state.sessions.filter(s => s.taskId === t.id && s.endedAt).sort((a,b) => b.startedAt-a.startedAt);
  $('#detail').innerHTML = `<div class="detail-head"><div><i class="badge ${isStudy(t) ? 'study' : ''}">${t.module}</i><h2>${escapeHtml(t.title)}</h2><p>${t.start}${t.end ? `–${t.end}` : ''} · ${t.kind === 'point' ? '时间点事项' : t.kind === 'open' ? '无固定结束' : duration(plannedSeconds(t))}</p></div><button class="icon-btn" id="editTask">✎</button></div>${t.choice ? `<div class="info-row"><span>当日选择</span><b>${escapeHtml(t.choice)}</b></div>` : ''}<div class="note-box"><span>备注</span><p>${escapeHtml(t.note || '暂无备注')}</p></div><div class="status-picker"><span>完成状态</span><div>${Object.entries(STATUS).map(([k,v]) => `<button data-status="${k}" class="${t.status === k ? 'active' : ''}">${v}</button>`).join('')}</div></div>${isStudy(t) ? `<section class="timer-card"><span>${active ? state.timer.runningSince ? '正在计时' : '计时已暂停' : '实际学习时间'}</span><strong id="timerValue">${clock(seconds)}</strong><div class="timer-actions">${active ? `<button class="secondary" id="pauseTimer">${state.timer.runningSince ? '暂停' : '继续'}</button><button class="primary" id="endTimer">结束并记录</button>` : `<button class="primary wide" id="startTimer">▷ 开始计时</button>`}</div><small>计时和完成状态相互独立；到点不会自动开始。</small></section><section class="sessions"><h3>练习记录</h3>${sessionList.length ? sessionList.map(s => `<div><span>${new Date(s.startedAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Shanghai'})}</span><label><input type="number" min="0" data-session="${s.id}" value="${Math.round(s.durationSeconds/60)}" /> 分钟</label></div>`).join('') : '<p class="muted">还没有计时记录</p>'}</section>` : '<div class="non-study">生活安排不计入学习时长统计。</div>'}`;
  $('#editTask').onclick = () => openTask(t); document.querySelectorAll('[data-status]').forEach(b => b.onclick = async () => { t.status = b.dataset.status; await persistDay('状态已保存'); render(); });
  $('#startTimer')?.addEventListener('click', () => startTimer(t)); $('#pauseTimer')?.addEventListener('click', togglePause); $('#endTimer')?.addEventListener('click', endTimer); document.querySelectorAll('[data-session]').forEach(i => i.onchange = () => correctSession(i));
}
function clock(s) { s=Math.floor(s); return [Math.floor(s/3600), Math.floor(s%3600/60), s%60].map(x=>String(x).padStart(2,'0')).join(':'); }
function escapeHtml(v='') { const d=document.createElement('div'); d.textContent=v; return d.innerHTML; }
async function startTimer(t) { if (state.timer && state.timer.taskId !== t.id) { notify('已有其他任务正在计时，请先暂停或结束当前计时。', true); return; } state.timer = { taskId:t.id, date:state.date, startedAt:Date.now(), runningSince:Date.now(), accumulatedSeconds:0 }; await db.saveTimer(state.timer); render(); }
async function togglePause() { if (state.timer.runningSince) { state.timer.accumulatedSeconds = elapsed(state.timer); state.timer.runningSince = null; } else state.timer.runningSince = Date.now(); await db.saveTimer(state.timer); render(); }
async function endTimer() { const timer=state.timer, secs=elapsed(timer); const id=`session-${timer.taskId}-${timer.startedAt}`; if (!state.sessions.some(s=>s.id===id)) { const s={id,taskId:timer.taskId,date:timer.date,startedAt:timer.startedAt,endedAt:Date.now(),durationSeconds:secs}; await db.saveSession(s); if(timer.date===state.date) state.sessions.push(s); } state.timer=null; await db.saveTimer(null); render(); notify('本次练习已记录，请选择任务完成状态。'); }
async function correctSession(input) { const s=state.sessions.find(x=>x.id===input.dataset.session); s.durationSeconds=Math.max(0,Number(input.value)*60); await db.saveSession(s); render(); notify('练习时长已修正'); }

function formTask() { const f=$('#taskForm'), data=Object.fromEntries(new FormData(f)); const old=state.day.tasks.find(t=>t.id===data.id); return {...old,id:data.id||uid('task'),title:data.title,module:data.module,kind:data.kind,start:data.start,end:data.kind==='range'?data.end:'',note:data.note,reminder:f.reminder.checked,status:old?.status||'todo',choice:data.choice||'',choices:old?.choices}; }
function showConflicts() { const c=conflictsFor(formTask(),state.day.tasks); $('#conflicts').classList.toggle('hidden',!c.length); $('#conflicts').textContent=c.length?`时间与“${c.map(x=>x.title).join('、')}”重叠。仍可保存，请自行调整安排。`:''; }
function openTask(t=null) { const f=$('#taskForm'); f.reset(); f.id.value=t?.id||''; f.title.value=t?.title||''; f.module.value=t?.module||'生活'; f.kind.value=t?.kind||'range'; f.start.value=t?.start||'09:00'; f.end.value=t?.end||'10:00'; f.note.value=t?.note||''; f.reminder.checked=t?.reminder||false; $('#formTitle').textContent=t?'编辑任务':'新增任务'; $('#deleteTask').classList.toggle('hidden',!t); const wrap=$('#choiceWrap'); wrap.classList.toggle('hidden',!t?.choices); if(t?.choices){f.choice.innerHTML=t.choices.map(x=>`<option ${x===t.choice?'selected':''}>${x}</option>`).join('');} $('#taskDialog').showModal(); showConflicts(); }
$('#taskForm').addEventListener('input', showConflicts); $('#taskForm').addEventListener('submit', async e => { if(e.submitter?.value==='cancel')return; e.preventDefault(); const t=formTask(); if(t.kind==='range'&&(!t.end||t.end<=t.start)){notify('结束时间必须晚于开始时间',true);return;} const i=state.day.tasks.findIndex(x=>x.id===t.id); i>=0?state.day.tasks[i]=t:state.day.tasks.push(t); await persistDay(); $('#taskDialog').close(); state.selected=t.id; render(); });
$('#deleteTask').onclick=async()=>{const id=$('#taskForm').id.value;if(!confirm('删除这项当天任务？已有计时记录会保留在备份中。'))return;state.day.tasks=state.day.tasks.filter(x=>x.id!==id);state.selected=null;await persistDay('任务已删除');$('#taskDialog').close();render();};
$('#addTask').onclick=()=>openTask(); $('#datePicker').onchange=e=>loadDate(e.target.value); $('#todayBtn').onclick=()=>loadDate(todayBJ()); const shift=n=>{const d=new Date(`${state.date}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+n);loadDate(fmtDate(d));}; $('#prevDay').onclick=()=>shift(-1);$('#nextDay').onclick=()=>shift(1);
$('#templateBtn').onclick=()=>{$('#templateForm').effectiveDate.value=state.date<todayBJ()?todayBJ():state.date;$('#templateDialog').showModal();}; $('#templateForm').onsubmit=async e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const date=e.currentTarget.effectiveDate.value;if(date<todayBJ()&&!confirm('生效日期早于今天，但仍不会覆盖已有每日记录。继续吗？'))return;await db.saveTemplate({id:uid('template'),effectiveDate:date,tasks:clone(state.day.tasks).map(t=>({...t,status:'todo'})),createdAt:Date.now()});$('#templateDialog').close();notify(`新模板将从 ${date} 起用于尚未建立的计划`);};
document.querySelectorAll('[data-later]').forEach(b=>b.onclick=()=>notify(`${b.dataset.later}模块后续接入，本阶段没有无效占位功能。`)); $('#settingsBtn').onclick=()=>$('#settingsDialog').showModal();
$('#exportBtn').onclick=async()=>{const data=await db.exportAll();const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=`学习系统备份-${todayBJ()}.json`;a.click();URL.revokeObjectURL(a.href);};
$('#importFile').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(data.schemaVersion!==1||!Array.isArray(data.templates)||!Array.isArray(data.days))throw new Error('备份格式不兼容');state.pendingImport=data;$('#importChoice').classList.remove('hidden');}catch(err){notify(`无法读取备份：${err.message}`,true);}};
$('#mergeImport').onclick=async()=>{await db.importMerged(state.pendingImport);$('#settingsDialog').close();await loadDate(state.date);notify('备份已合并；相同 ID 的本机记录优先保留');}; $('#replaceImport').onclick=async()=>{if(!confirm('确定用备份替换此设备的全部数据吗？建议先导出当前数据。'))return;await db.replaceAll(state.pendingImport);$('#settingsDialog').close();await loadDate(state.date);notify('已用备份替换本机数据');};
setInterval(()=>{if(state.timer?.runningSince){const val=$('#timerValue');if(val)val.textContent=clock(taskActualSeconds(state.selected,state.sessions)+elapsed(state.timer));}},1000);
window.addEventListener('unhandledrejection',e=>notify(`操作失败，页面中的内容仍保留：${e.reason?.message||e.reason}`,true));
await db.initialize(todayBJ()); await loadDate(state.date);
